// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vaihyumaqzvqoyotxtfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhaWh5dW1hcXp2cW95b3R4dGZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyOTc4NTMsImV4cCI6MjA1NDg3Mzg1M30.zPfv_eYoYLCfJD8UzSpJEPNCV2lbCCAknfb1vcpdTc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);